# Generated by Django 3.1.4 on 2020-12-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('tipo_unidade', models.CharField(choices=[('u', 'Unidade'), ('m', 'Metros'), ('o', 'Outro')], max_length=1)),
                ('quantidade_ano', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem_material')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('desenho', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada', models.DateTimeField()),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('responsavel_retirada', models.CharField(blank=True, max_length=50, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('em_estoque', models.BooleanField()),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.material')),
            ],
        ),
    ]
