# Generated by Django 3.1.4 on 2020-12-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rs', models.IntegerField()),
                ('numero_os', models.IntegerField()),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='MatServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.material')),
                ('numero_rs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico')),
            ],
        ),
    ]
